---

- name: APT | Install nodesource dependencies
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - curl

- name: Install nodejs repo
  shell: "curl -sL https://deb.nodesource.com/setup_{{ nodesource_nodejs_version }}.x | sudo -E bash -"

- name: APT | Install nodejs
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - nodejs

...
