---

- name: APT | Install nodesource dependencies
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - curl
    - ca-certificates
    - gnupg

- name: APT | Install gpg key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present

- name: Apt | Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodesource_nodejs_version }}.x nodistro main"
    state: present
    filename: nodesource

- name: APT | Install nodejs
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - nodejs

...
