---

- name: Load RedHat.yml
  include: RedHat.yml
  when:
  - ansible_facts['os_family'] == "RedHat"

- name: Load Debian.yml
  include: Debian.yml
  when:
  - ansible_facts['os_family'] == "Debian"

...
