---
- name: Install
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:
    nodesource_nodejs_version: '22'

  roles:
  - name: andrelohmann.root_colored_prompt
  - name: ansible-role-nodesource
...
