---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  vars:
    nodesource_nodejs_version: '20'
  tasks:
  - name: "Include andrelohmann.nodesource"
    include_role:
      name: "andrelohmann.nodesource"
...
